---
- name: Ensure docker group exists
  become: yes
  group:
    name: docker
    state: present

- name: Ensure '{{ raspberry_user }}' user is added to docker group
  become: yes
  user:
    name: '{{ raspberry_user }}'
    groups: docker
    append: yes

- name: Ensure aufs-tools apt preferences is set to not instal
  become: yes
  copy:
    dest: /etc/apt/preferences.d/aufs-tools
    src: files/aufs-tools

- name: Ensure docker is installed
  include_role:
    name: geerlingguy.docker
  vars:
    ansible_become: yes
  register: docker_install

- name: Ensure docker python library is installed
  become: yes
  package:
    name: python3-docker
    state: present
    
- name: Ensure Docker api is started
  wait_for:
    timeout: 60

- name: provide custom environment variables
  template:
    src: pihole.env.j2
    dest: "{{ ansible_user_dir}}/etc-pihole.env"

- name: Ensure pihole docker container is running
  become: yes
  docker_container:
    name: pihole
    image: "pihole/pihole:{{ pihole_docker_tag }}"
    state: started
    restart: no
    restart_policy: unless-stopped
    ports:
    - '53:53/udp' #dns
    - '53:53/tcp' #dns
    - '67:67/udp' #dhcp
    - '80:80/tcp' #web interface
    - '443:443/tcp' #web interface
    volumes:
    - ./etc-pihole/:/etc/pihole/
    - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    env_file: "{{ ansible_user_dir}}/etc-pihole.env"
    env:
      DNS1: '{{ dns_server1 }}'
      DNS2: '{{ dns_server2 }}'
      WEBPASSWORD: "{{ pihole_admin_password }}"
